# Generated by Django 5.1.3 on 2024-11-21 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_guestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
